kind: Service
apiVersion: v1
metadata:
  name: fetch
spec:
  type: NodePort
  selector:
   app: fetch
   color: blue
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30006
    name: http
