apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
   app: ui
spec:
  replicas: 1
  selector:
   matchLabels:
    app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: pmorpari/ui_container:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: ui
spec:
  type: NodePort
  selector:
   app: ui
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30004
    name: http
