apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-blue
  labels:
   app: ui
spec:
  replicas: 1
  selector:
   matchLabels:
    app: ui
  template:
    metadata:
      labels:
        app: ui
        color: blue
    spec:
      containers:
      - name: ui
        image: pmorpari/ui-blue
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

