kind: Service
apiVersion: v1
metadata:
  name: ui
spec:
  type: NodePort
  selector:
   app: ui
   color: red
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30004
    name: http
