kind: Service
apiVersion: v1
metadata:
  name: upload-service
spec:
  type: NodePort
  selector:
   app: upload-service
   color: blue
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    nodePort: 30003
